-- this script creates a new database with a unique autogenerated primary key
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
USE hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VARCHAR(256) NOT NULL
);